"""Validated numerical configuration extracted from notebook Combos 1-48."""

from pathlib import Path

SEED = 42

REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
ASSETS_DIR = REPOSITORY_ROOT / "assets"
ARTIFACTS_DIR = REPOSITORY_ROOT / "artifacts"
SEABED_IMAGE_PATH = ASSETS_DIR / "sample_map.png"

WIDTH = 1448
HEIGHT = 1086
CHANNELS = 3

NUM_UUVS = 4
FOV_WIDTH = 128
FOV_HEIGHT = 128
STEP_SIZE = 8
ROLLOUT_STEPS = 50
ROLLOUT_STEP_SIZE = 32
NUM_RESOURCES = 20
RESOURCE_COUNT_MIN = 10
RESOURCE_COUNT_MAX = 25
RESOURCE_CLASSES = ("A", "B", "C")
RESOURCE_SCENARIO_SEED = None

ACTION_UP = 0
ACTION_RIGHT = 1
ACTION_DOWN = 2
ACTION_LEFT = 3
ACTION_HOLD = 4
ACTION_NAMES = {
    ACTION_UP: "UP",
    ACTION_RIGHT: "RIGHT",
    ACTION_DOWN: "DOWN",
    ACTION_LEFT: "LEFT",
}
SAFETY_ACTION_NAMES = {**ACTION_NAMES, ACTION_HOLD: "HOLD"}
ACTION_DELTAS = {
    ACTION_UP: (0, -STEP_SIZE),
    ACTION_RIGHT: (STEP_SIZE, 0),
    ACTION_DOWN: (0, STEP_SIZE),
    ACTION_LEFT: (-STEP_SIZE, 0),
}
SAFETY_ACTION_SET = (
    ACTION_UP,
    ACTION_RIGHT,
    ACTION_DOWN,
    ACTION_LEFT,
    ACTION_HOLD,
)

UUV_SPAWN_SEED = None
MIN_SPAWN_SEPARATION = 2 * max(FOV_WIDTH, FOV_HEIGHT)
MAX_SPAWN_ATTEMPTS = 10_000
MOTION_SEED = None

MIN_FRONTIER_REGION_SIZE = 10
FRONTIER_CANDIDATE_SPACING = 128.0
MAX_FRONTIER_CANDIDATES = 12
W_INFORMATION = 1.00
W_DISTANCE = 0.35
W_REDUNDANCY = 0.25
MAP_DIAGONAL = float((WIDTH**2 + HEIGHT**2) ** 0.5)
GOAL_PURSUIT_MAX_STEPS = 20
GOAL_REACHED_RADIUS = ROLLOUT_STEP_SIZE
AUTONOMOUS_PLANNING_CYCLES = 8
MAX_STEPS_PER_GOAL = 20

SAFE_SEPARATION = 128.0
SAFE_AUTONOMY_STEPS = 120
COMMUNICATION_RANGE = 400.0
COOPERATIVE_MISSION_STEPS = 180

TASK_DEDUPLICATION_DISTANCE = 128.0
ALLOC_MISSION_STEPS = 180
ALLOCATION_INTERVAL = 12
ALLOCATION_COOLDOWN = 4
GOAL_MIN_UNKNOWN_RATIO = 0.15
MIN_ASSIGNED_GOAL_SEPARATION = 128.0
TASK_OVERLAP_WEIGHT = 0.65

PACKET_LOSS_PROBABILITY = 0.25
PACKET_LOSS_SEED = None
MONTE_CARLO_PACKETS = 10_000
MONTE_CARLO_TOLERANCE = 0.03
MIN_COMM_DELAY = 1
MAX_COMM_DELAY = 5
LATENCY_TEST_SEED = None
LATENCY_MONTE_CARLO_SAMPLES = 10_000
LATENCY_MEAN_TOLERANCE = 0.10
BLACKOUT_START_PROBABILITY = 0.02
BLACKOUT_MIN_DURATION = 10
BLACKOUT_MAX_DURATION = 30
BLACKOUT_TEST_SEED = None
UNIFIED_CHANNEL_STEPS = 120
UNIFIED_CHANNEL_SEED = 310031
DEGRADED_MISSION_STEPS = 180
DEGRADED_CHANNEL_SEED = 320032

FAILURE_MISSION_STEPS = 180
FAILED_UUV_ID = 1
FAILURE_TIME = 60
FAILURE_CHANNEL_SEED = 330033
REASSIGN_MISSION_STEPS = 180
FAILED_UUV_ID_34 = 1
FAILURE_TIME_34 = 60
REASSIGN_CHANNEL_SEED = 340034
REASSIGN_INFO_WEIGHT = 0.65
REASSIGN_DISTANCE_WEIGHT = 0.35
HEARTBEAT_TEST_STEPS = 130
HEARTBEAT_FAILURE_UUV = 1
HEARTBEAT_FAILURE_TIME = 50
HEARTBEAT_TIMEOUT = 40
HEARTBEAT_TEST_SEED = 350035
RECOVERY_MISSION_STEPS_36 = 320
FAILED_UUV_ID_36 = 1
PHYSICAL_FAILURE_TIME_36 = 50
HEARTBEAT_SUSPICION_THRESHOLD_36 = 40
MAJORITY_CONFIRMATIONS_36 = 2
RECOVERY_CHANNEL_SEED_36 = 360036
RECOVERY_INFO_WEIGHT_36 = 0.65
RECOVERY_DISTANCE_WEIGHT_36 = 0.35
ORPHAN_FAILED_UUV_CLEARANCE_36 = SAFE_SEPARATION + ROLLOUT_STEP_SIZE

LEARN_DATASET_SEED = 370037
SYNTHETIC_STATES_PER_UUV = 80
MAX_DATASET_CANDIDATES = 20
MIN_SYNTHETIC_RETENTION = 0.20
MAX_SYNTHETIC_RETENTION = 1.00
FEATURE_COLUMNS_37 = [
    "information_ratio",
    "distance_norm",
    "redundancy_ratio",
    "local_coverage",
    "known_coverage",
    "comm_degree_norm",
]
TARGET_COLUMN_37 = "classical_utility"
TRAIN_SEED_38 = 380038
BATCH_SIZE_38 = 256
NUM_EPOCHS_38 = 150
LEARNED_MISSION_STEPS_40 = 180
LEARNED_CHANNEL_SEED_40 = 320032
HYBRID_LEARNED_MARGIN_MIN_43 = 0.03
HYBRID_CLASSICAL_REGRET_MAX_43 = 0.02

BENCHMARK_SEEDS_42 = [420001, 420002, 420003, 420004, 420005]
BENCHMARK_STEPS_42 = 180
BENCHMARK_SEEDS_44 = [420001, 420002, 420003, 420004, 420005]
BENCHMARK_STEPS_44 = 180

SHOWCASE_STEPS_45 = 180
SHOWCASE_SEED_45 = 450045
FRAME_INTERVAL_45 = 2
GIF_FPS_45 = 8
SHOWCASE_STEPS_46 = 260
SHOWCASE_SEED_46 = 460046
FAILED_UUV_ID_46 = 1
PHYSICAL_FAILURE_TIME_46 = 70
HEARTBEAT_THRESHOLD_46 = 40
MAJORITY_CONFIRMATIONS_46 = 2
FRAME_INTERVAL_46 = 2
GIF_FPS_46 = 8

HYBRID_GIF_NAME = "multiuuv_hybrid_mission_prototype.gif"
FAULT_GIF_NAME = "multiuuv_fault_recovery_showcase_prototype.gif"
METRICS_CSV_NAME = "multiuuv_final_metrics_prototype.csv"
SUMMARY_JSON_NAME = "multiuuv_final_summary_prototype.json"
MODEL_NAME = "frontier_value_model_prototype.pt"
